### ISSUE TITLE
Remove pathlib dependency

### ISSUE THREAD

**Issue by owenlamont** [conda-forge/pyprojroot-feedstock#2]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:  pyprojroot unnecessarily installs pathlib

Pathlib has been part of the standard library since Python 3.4 - and the minimum Python version that conda-forge supports is 3.6 as I understand - so forcing users to install this package is unnecessary. I recommend removing pathlib as a requirement and explicitly setting a minimum Python version which I think the conda-forge linter now requires anyway.

**Comment by achimgaedke** [comment]
#4 contains this fix as well

**Comment by achimgaedke** [comment]
fixed and release
